---
- name: Install packages with chocolatey
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - sql-server-express
    - sql-server-management-studio

- name: Check if service mssql$sqlexpress exists
  ansible.windows.win_service_info:
    name: mssql$sqlexpress
  register: svc_mssql_exists

- name: Loop until service mssql$sqlexpress exists
  ansible.windows.win_service_info:
    name: mssql$sqlexpress
  register: svc_mssql_loop
  until: svc_mssql_loop.exists == true
  when: svc_mssql_exists.exists == false
  retries: 20
  delay: 30

# Needs to be this way. Citrix van't be installed if simply using chocolatey from Ansible to install SQL. Some rights problem.
